# Generated by Django 5.1.5 on 2025-02-03 14:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question in your primary language (English)')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(help_text='Enter the answer in your primary language (English)')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations are automatically generated and stored here')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
