# Generated by Django 5.1.5 on 2025-02-01 17:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question in English')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(help_text='Enter the answer in English')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('question_bn', models.TextField(blank=True, null=True, verbose_name='Question (Bengali)')),
                ('question_es', models.TextField(blank=True, null=True, verbose_name='Question (Spanish)')),
                ('question_fr', models.TextField(blank=True, null=True, verbose_name='Question (French)')),
                ('answer_hi', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (Hindi)')),
                ('answer_bn', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (Bengali)')),
                ('answer_es', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (Spanish)')),
                ('answer_fr', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (French)')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
